version: "3.4"
services:
  docker:
    image: homework25:latest
    container_name: docker-compose
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    restart:
      always

