version: "3.4"
services:
  docker:
    container_name: docker-compose
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    restart:
      always

  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ./somevol:/app2:rw
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    restart:
      always
    depends_on:
      - docker

  db:
    image: 'postgres:${TAG}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
    postgres_data:
  
