version: "3.4"
services:
  docker:
    container_name: docker-compose
    build: ./dockerfile
    ports:
      - "5000:5000"
    restart:
      always

  nginx:
    container_name: nginx
    build: ./dockerfile-nginx
    volumes:
      - ./somevol:/app2:rw
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    restart:
      always
    depends_on:
      - docker
