replicaCount: 2
image:
  repository: gosuooops/dos14-authz
  pullPolicy: IfNotPresent
  tag: 339faa036722601916788dd19e17376b1c84c10c
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: authzacc
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  protocol: TCP
  targetport: 80
ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  hosts:
    host: api.gigachad.smodata.net
    http:
      paths:
        path: /authz(.*)
        pathType: ImplementationSpecific
      port: 80
  tls:
    secretName: myapp-tls-secret
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts:
  name: nginx-config
  mountPath: /etc/nginx
nodeSelector: {}
tolerations: []
affinity: {}
deployment:
  strategy:
    type: RollingUpdate
    maxSurge: 2
  template:
    specNginx:
      name: nginx
      image: nginx:1.25.2
      ports:
        containerPort: 80
        name: http
        protocol: TCP
      volume_configMap: nginx-config
        
envs:
  - name: PG_HOST
    value: omegabank-rds-tf.cearikylb8tb.eu-west-1.rds.amazonaws.com
  - name: PG_PORT
    value: "5432"
  - name: PG_DB
    value: gigachad
  - name: PG_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: gigachad-db-creds
  - name: PG_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: gigachad-db-creds

labels:
  app: authz
  bank: gigachad
  env: prd
