- name: Set environment variables
  template:
    src: .env
    dest: ../docker-compose.yaml
    owner: root
    group: root
    mode: '0644'
    
- name: Clone repository git
  become: true
  git:
    repo: https://github.com/GosuOoops/dos14--Kuchko_Evgenii-git-flow.git
    dest: /home/authz/git
    version: "{{ git_branch }}"
    force: yes
  register: gitclone

- name: install pip
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker-compose
  become: true
  apt:
    name: docker-compose
    state: present

- name: Add group for authz
  become: true
  user:
    name: authz
    groups: docker
    append: yes

- name: build container image
  become: true
  command:
    cmd: "docker-compose build --no-cache"
    chdir: /home/authz/git
  when: gitclone.changed

- name: Run container
  become: true
  command:
    cmd: "docker-compose -f docker-compose.yaml up -d"
    chdir: /home/authz/git

