- name: Clone repository git
  become: true
  git:
    repo: https://github.com/GosuOoops/dos14--Kuchko_Evgenii-git-flow.git
    dest: /home/authz/git
    version: master
    force: yes
- name: Poetry install
  become: true
  ansible.builtin.shell:
    chdir: /home/authz/git
    cmd: poetry install
  args:
    executable: /bin/bash
  changed_when: false
- name: Create service
  become: true
  template:
    src: my.service.j2
    dest: /etc/systemd/system/my.service
    owner: root
    group: root
    mode: '0755'
- name: Start my.service
  become: true
  command: systemctl start my.service
- name: Check start my.service
  become: true
  service:
    name: my.service
    state: started
    enabled: true
