- name: Create group
  group:
    name: authz
  become: true
- name: Create user
  user:
    name: authz
    group: authz
    groups: root
    append: yes
    state: present
    shell: /bin/bash
    home: /home/authz
  become: true
  become_user: root
